AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Demo of Spring Boot 2 running on Amazon Lambda.

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL
  Function:
    Runtime: java8
    Timeout: 60
    MemorySize: 1512

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.sheepduke.demo.hello.LambdaHandler::handleRequest
      CodeUri: build/distributions/demo-hello-1.0.0.zip
      Policies: AWSLambdaBasicExecutionRole
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
